version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authdb
    ports:
      - "3306:3306"
    networks:
      - dev-network
    healthcheck:
      test: ["CMD-SHELL", "pgrep mysqld"]
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 120s



  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: authdb
    networks:
      - dev-network


networks:
  dev-network:
    driver: bridge